name: Python greetings application workflow
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  install-pip-deps:
    runs-on: "self-hosted"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          ref: 'main'
          path: 'python-greetings'
      - uses: actions/checkout@v4
        with:
          repository: ZaliveVerty/LabDarbs_0406_1
          ref: 'main'
          path: 'LabDarbs_0406_1'
          sparse-checkout: |
            .github
      - uses: ./LabDarbs_0406_1/.github/actions/build
  deploy-to-dev:
    runs-on: "self-hosted"
    needs: [install-pip-deps]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          ref: 'main'
          path: 'python-greetings'
      - uses: actions/checkout@v4
        with:
          repository: ZaliveVerty/LabDarbs_0406_1
          ref: 'main'
          path: 'LabDarbs_0406_1'
          sparse-checkout: |
            .github
      - uses: ./LabDarbs_0406_1/.github/actions/deploy
        with:
          environment: 'dev'
          port: '7001'
          type: 'development'
  tests-on-dev:
    runs-on: "self-hosted"
    needs: [deploy-to-dev]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          ref: 'main'
          path: 'mtararujs/course-js-api-framework'
      - uses: actions/checkout@v4
        with:
          repository: ZaliveVerty/LabDarbs_0406_1
          ref: 'main'
          path: 'LabDarbs_0406_1'
          sparse-checkout: |
            .github
      - uses: ./LabDarbs_0406_1/.github/actions/deploy
        with:
          environment: 'dev'
          test-suite:: 'greetings'
          type: 'development'
  deploy-to-staging:
    runs-on: "self-hosted"
    needs: [tests-on-dev]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          ref: 'main'
          path: 'python-greetings'
      - uses: actions/checkout@v4
        with:
          repository: ZaliveVerty/LabDarbs_0406_1
          ref: 'main'
          path: 'LabDarbs_0406_1'
          sparse-checkout: |
            .github
      - uses: ./LabDarbs_0406_1/.github/actions/deploy
        with:
          environment: 'stg'
          port: '7002'
          type: 'staging'
  tests-on-staging:
    runs-on: "self-hosted"
    needs: [deploy-to-staging]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          ref: 'main'
          path: 'mtararujs/course-js-api-framework'
      - uses: actions/checkout@v4
        with:
          repository: ZaliveVerty/LabDarbs_0406_1
          ref: 'main'
          path: 'LabDarbs_0406_1'
          sparse-checkout: |
            .github
      - uses: ./LabDarbs_0406_1/.github/actions/deploy
        with:
          environment: 'stg'
          test-suite:: 'greetings'
          type: 'staging'
  deploy-to-preprod:
    runs-on: "self-hosted"
    needs: [tests-on-staging]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          ref: 'main'
          path: 'python-greetings'
      - uses: actions/checkout@v4
        with:
          repository: ZaliveVerty/LabDarbs_0406_1
          ref: 'main'
          path: 'LabDarbs_0406_1'
          sparse-checkout: |
            .github
      - uses: ./LabDarbs_0406_1/.github/actions/deploy
        with:
          environment: 'preprod'
          port: '7003'
          type: 'pre-production'
  tests-on-preprod:
    runs-on: "self-hosted"
    needs: [deploy-to-preprod]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          ref: 'main'
          path: 'mtararujs/course-js-api-framework'
      - uses: actions/checkout@v4
        with:
          repository: ZaliveVerty/LabDarbs_0406_1
          ref: 'main'
          path: 'LabDarbs_0406_1'
          sparse-checkout: |
            .github
      - uses: ./LabDarbs_0406_1/.github/actions/deploy
        with:
          environment: 'preprod'
          test-suite:: 'greetings'
          type: 'pre-production'
  deploy-to-prod:
    runs-on: "self-hosted"
    needs: [tests-on-preprod]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          ref: 'main'
          path: 'python-greetings'
      - uses: actions/checkout@v4
        with:
          repository: ZaliveVerty/LabDarbs_0406_1
          ref: 'main'
          path: 'LabDarbs_0406_1'
          sparse-checkout: |
            .github
      - uses: ./LabDarbs_0406_1/.github/actions/deploy
        with:
          environment: 'prod'
          port: '7004'
          type: 'production'
  Tests-on-prod:
    runs-on: "self-hosted"
    needs: [deploy-to-prod]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          ref: 'main'
          path: 'mtararujs/course-js-api-framework'
      - uses: actions/checkout@v4
        with:
          repository: ZaliveVerty/LabDarbs_0406_1
          ref: 'main'
          path: 'LabDarbs_0406_1'
          sparse-checkout: |
            .github
      - uses: ./LabDarbs_0406_1/.github/actions/deploy
        with:
          environment: 'prod'
          test-suite:: 'greetings'
          type: 'production'